name: Latest Blog Posts
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Website Posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://nabeelvalley.co.za/feed/rss.xml
          date_format: mm dd yyyy
          template: "$newline- [$date- $title]($url)"
          commit_message: ":robot: github action update"
          
